// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	model "github.com/stasBigunenko/monorepa/model"
	mock "github.com/stretchr/testify/mock"
)

// ItemsGrpcService is an autogenerated mock type for the ItemsGrpcService type
type ItemsGrpcService struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: name
func (_m *ItemsGrpcService) GetItems(name string) ([]model.Item, error) {
	ret := _m.Called(name)

	var r0 []model.Item
	if rf, ok := ret.Get(0).(func(string) []model.Item); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
