// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// ParseToken provides a mock function with given fields: tokenPart
func (_m *TokenService) ParseToken(tokenPart string) error {
	ret := _m.Called(tokenPart)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenPart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
