version: "3.1"

services: 
  auth:
    container_name: "auth"
    build: 
      context: "./"
      dockerfile: "./docker/auth.Dockerfile"
    environment:
      # serever
      SERVER_HOST: ''
      SERVER_PORT: '8080'
      
      # shutdown
      Server_Cancel_Timeout: '5'

      # JWT config
      TOKEN_EXPIRE: '10'

      # certificates
      CERT_VERSION: '1'
      CERT_PATH: './pkg/storage/certificates'
    ports: 
      - "8080:8080"

  http:
    container_name: "http"
    build: 
      context: "./"
      dockerfile: "./docker/http.Dockerfile"
    ports: 
      - 8081:8081
    environment:    
      HTTP_ADDRESS: :8081
      JWT_ADDRESS: auth:8080
      GRPC_ADDRESS: grpc:50051
    links:
      - "auth:auth"
      - "grpc:grpc"
    depends_on:
          - "grpcAccount"
          - "grpcUser"

  grpcAccount:
    container_name: "grpcAccount"
    build: 
      context: "./"
      dockerfile: "./docker/grpcAcc.Dockerfile"
    environment:
      GRPC_SERV_ADDRESS: ':50053'
    ports: 
      - "50053:50053"


  grpcUser:
    container_name: "grpcUser"
    build: 
      context: "./"
      dockerfile: "./docker/grpcAcc.Dockerfile"
    environment:
      GRPC_SERV_ADDRESS: ':50052'
    ports: 
      - "50052:50052"
