// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	storage "monorepa/pkg/storage"

	mock "github.com/stretchr/testify/mock"
)

// StorageInterface is an autogenerated mock type for the StorageInterface type
type StorageInterface struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: username
func (_m *StorageInterface) GetItems(username string) ([]storage.Storage, error) {
	ret := _m.Called(username)

	var r0 []storage.Storage
	if rf, ok := ret.Get(0).(func(string) []storage.Storage); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Storage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
