// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package accountInt

import (
	context "context"

	model "github.com/stasBigunenko/monorepa/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccInterface is an autogenerated mock type for the AccInterface type
type AccInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AccInterface) Create(_a0 context.Context, _a1 uuid.UUID) (model.Account, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Account
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *AccInterface) Delete(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *AccInterface) Get(_a0 context.Context, _a1 uuid.UUID) (model.Account, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Account
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0
func (_m *AccInterface) GetAll(_a0 context.Context) ([]model.Account, error) {
	ret := _m.Called(_a0)

	var r0 []model.Account
	if rf, ok := ret.Get(0).(func(context.Context) []model.Account); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: _a0, _a1
func (_m *AccInterface) GetUser(_a0 context.Context, _a1 uuid.UUID) ([]model.Account, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.Account
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *AccInterface) Update(_a0 context.Context, _a1 model.Account) (model.Account, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Account
	if rf, ok := ret.Get(0).(func(context.Context, model.Account) model.Account); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Account) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
