// Code generated by mockery (devel). DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServerActions is an autogenerated mock type for the ServerActions type
type MockServerActions struct {
	mock.Mock
}

// GetRouters provides a mock function with given fields:
func (_m *MockServerActions) GetRouters() {
	_m.Called()
}

// ServerAddrConfig provides a mock function with given fields:
func (_m *MockServerActions) ServerAddrConfig() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: _a0
func (_m *MockServerActions) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
