// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/stasBigunenko/monorepa/pkg/grpc/proto"
)

// GrpcServiceClient is an autogenerated mock type for the GrpcServiceClient type
type GrpcServiceClient struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: ctx, in, opts
func (_m *GrpcServiceClient) GetItems(ctx context.Context, in *proto.Username, opts ...grpc.CallOption) (*proto.Items, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.Items
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Username, ...grpc.CallOption) *proto.Items); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Items)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.Username, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
