// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/stasBigunenko/monorepa/pkg/grpc/proto"
	mock "github.com/stretchr/testify/mock"
)

// GrpcServiceServer is an autogenerated mock type for the GrpcServiceServer type
type GrpcServiceServer struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: _a0, _a1
func (_m *GrpcServiceServer) GetItems(_a0 context.Context, _a1 *proto.Username) (*proto.Items, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.Items
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Username) *proto.Items); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Items)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.Username) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGrpcServiceServer provides a mock function with given fields:
func (_m *GrpcServiceServer) mustEmbedUnimplementedGrpcServiceServer() {
	_m.Called()
}
