// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGrpcServiceServer is an autogenerated mock type for the UnsafeGrpcServiceServer type
type UnsafeGrpcServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGrpcServiceServer provides a mock function with given fields:
func (_m *UnsafeGrpcServiceServer) mustEmbedUnimplementedGrpcServiceServer() {
	_m.Called()
}
